name: checklist
description: "Flutter Project for Checklist - Offline First"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  google_fonts: ^6.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  cbl: ^3.2.1
  cbl_flutter: ^3.1.3
  cbl_flutter_ce: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/